import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { compactNumber, dateOnly, money } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { buildExpirationReminder, normalizeWhatsAppPhone } from "@shared/whatsapp";
import { AlertTriangle, ArrowRight, BarChart3, CalendarDays, CheckCircle2, Copy, FileClock, MessageCircle, Plus, ShoppingBag, ThumbsDown, Trophy, WalletCards } from "lucide-react";
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { toast } from "sonner";
import { useLocation } from "wouter";

const STATUS_COLORS = { approved: "#10b981", pending: "#e0b928", rejected: "#ef4444" } as const;
const STATUS_ICONS = { approved: CheckCircle2, pending: FileClock, rejected: ThumbsDown } as const;
const STATUS_CARD_STYLE = { approved: "bg-emerald-500/15 text-emerald-700 dark:text-emerald-300", pending: "bg-amber-500/15 text-amber-700 dark:text-amber-300", rejected: "bg-red-500/15 text-red-700 dark:text-red-300" } as const;
const ALERT_STYLE = { expired: "border-red-500/25 bg-red-500/10 text-red-800 dark:text-red-200", today: "border-orange-500/25 bg-orange-500/10 text-orange-800 dark:text-orange-200", soon: "border-amber-500/25 bg-amber-500/10 text-amber-800 dark:text-amber-200", upcoming: "border-sky-500/25 bg-sky-500/10 text-sky-800 dark:text-sky-200" } as const;

function StatusCard({ status, count, value }: { status: "approved" | "pending" | "rejected"; count: number; value: number }) {
  const Icon = STATUS_ICONS[status];
  const label = status === "approved" ? "Aprovados" : status === "pending" ? "Pendentes" : "Rejeitados";
  return <Card className="overflow-hidden border-border/70 shadow-sm"><CardContent className="p-5"><div className="mb-6 flex items-start justify-between"><span className={`grid h-10 w-10 place-items-center rounded-xl ${STATUS_CARD_STYLE[status]}`}><Icon className="h-5 w-5" /></span><span className="text-[10px] font-bold uppercase tracking-[0.14em] text-muted-foreground">Status</span></div><p className="text-xs font-semibold text-muted-foreground">{label}</p><div className="mt-2 flex items-end justify-between gap-3"><p className="font-display text-2xl font-bold tracking-tight">{compactNumber(count)}</p><p className="mb-1 text-xs font-semibold text-muted-foreground">{money(value)}</p></div></CardContent></Card>;
}

export default function DashboardPage() {
  const [, setLocation] = useLocation();
  const { data, isLoading } = trpc.dashboard.useQuery();
  const chartData = data?.statusSummary ?? [];
  const expirationAlerts = data?.expirationAlerts ?? [];
  const reminderMessage = (alert: typeof expirationAlerts[number]) => buildExpirationReminder({ brand: data?.alertBrand || "Luminno", quoteNumber: alert.quoteNumber, clientName: alert.clientName, validUntil: alert.validUntil, daysRemaining: alert.daysRemaining, total: alert.total });
  const copyReminder = async (alert: typeof expirationAlerts[number]) => { try { await navigator.clipboard.writeText(reminderMessage(alert)); toast.success("Lembrete copiado para o WhatsApp"); } catch { toast.error("Não foi possível copiar o lembrete"); } };
  const sendReminder = async (alert: typeof expirationAlerts[number]) => { const phone = normalizeWhatsAppPhone(alert.phone || ""); if (phone) { window.open(`https://wa.me/${phone}?text=${encodeURIComponent(reminderMessage(alert))}`, "_blank", "noopener,noreferrer"); return; } await copyReminder(alert); toast.info("Telefone não cadastrado: lembrete copiado para enviar manualmente."); };
  const hasStatusData = chartData.some((entry) => entry.count > 0);
  return <div className="mx-auto max-w-7xl space-y-8">
    <section className="flex flex-col gap-4 rounded-3xl bg-[#181817] px-6 py-7 text-white shadow-xl shadow-black/10 md:flex-row md:items-end md:justify-between md:px-8"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.18em] text-[#f4d842]">Gestão comercial</p><h2 className="font-display text-2xl font-bold tracking-tight md:text-3xl">Orçamentos que iluminam decisões.</h2><p className="mt-2 max-w-xl text-sm leading-relaxed text-white/65">Acompanhe o desempenho comercial por status, monte propostas por ambiente e mantenha os dados da loja centralizados.</p></div><Button onClick={() => setLocation("/orcamentos/novo")} className="h-11 bg-[#f4d842] px-5 font-bold text-black hover:bg-[#ffea77]"><Plus className="mr-2 h-4 w-4" />Novo orçamento</Button></section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatusCard status="approved" count={data?.approvedCount ?? 0} value={data?.approvedValue ?? 0}/><StatusCard status="pending" count={data?.pendingCount ?? 0} value={data?.pendingValue ?? 0}/><StatusCard status="rejected" count={data?.rejectedCount ?? 0} value={data?.rejectedValue ?? 0}/><Card className="overflow-hidden border-border/70 shadow-sm"><CardContent className="p-5"><div className="mb-6 flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-500/15 text-violet-700 dark:text-violet-300"><ShoppingBag className="h-5 w-5" /></span><span className="text-[10px] font-bold uppercase tracking-[0.14em] text-muted-foreground">Média</span></div><p className="text-xs font-semibold text-muted-foreground">Ticket médio ativo</p><p className="mt-2 font-display text-2xl font-bold tracking-tight">{isLoading ? "—" : money(data?.averageTicket)}</p></CardContent></Card></section>

    <section className="grid gap-4 lg:grid-cols-2"><Card className="border-border/70 shadow-sm"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-sky-500/10 text-sky-700 dark:text-sky-300"><WalletCards className="h-5 w-5"/></span><div><p className="text-sm font-bold">Financeiro</p><p className="mt-1 text-xs text-muted-foreground">Saldo a receber: <b className="text-foreground">{money(data?.finance?.outstanding)}</b> · recebido no mês: <b className="text-emerald-700 dark:text-emerald-300">{money(data?.finance?.receivedThisMonth)}</b></p></div></div><Button size="sm" variant="outline" onClick={() => setLocation("/financeiro")}>Abrir financeiro <ArrowRight className="ml-2 h-3.5 w-3.5"/></Button></CardContent></Card><Card className="border-border/70 shadow-sm"><CardContent className="flex items-center gap-3 p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-red-500/10 text-red-700 dark:text-red-300"><CalendarDays className="h-5 w-5"/></span><div><p className="text-sm font-bold">Cobranças em atraso</p><p className="mt-1 text-xs text-muted-foreground">{data?.finance?.overdueCount ?? 0} cobrança(s) somando <b className="text-red-700 dark:text-red-300">{money(data?.finance?.overdueAmount)}</b>.</p></div></CardContent></Card></section>

    <section className="grid gap-6 lg:grid-cols-[1.05fr_0.95fr]"><Card className="border-border/70 shadow-sm"><CardContent className="p-6"><div className="mb-4 flex items-start justify-between"><div><p className="text-sm font-bold">Distribuição da carteira</p><p className="mt-1 text-xs text-muted-foreground">Quantidade de propostas por status comercial.</p></div><FileClock className="h-5 w-5 text-primary" /></div>{hasStatusData ? <div className="h-[260px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={chartData} dataKey="count" nameKey="label" innerRadius={56} outerRadius={88} paddingAngle={4}>{chartData.map((entry) => <Cell key={entry.key} fill={STATUS_COLORS[entry.key]} />)}</Pie><Tooltip formatter={(value: number) => [`${value} proposta(s)`, "Quantidade"]} /><text x="50%" y="47%" textAnchor="middle" dominantBaseline="middle" className="fill-foreground font-display text-[26px] font-bold">{compactNumber(chartData.reduce((sum, entry) => sum + entry.count, 0))}</text><text x="50%" y="58%" textAnchor="middle" dominantBaseline="middle" className="fill-muted-foreground text-[11px]">propostas</text></PieChart></ResponsiveContainer></div> : <div className="grid h-[260px] place-items-center rounded-2xl border border-dashed border-border text-center"><div><FileClock className="mx-auto h-7 w-7 text-muted-foreground"/><p className="mt-3 text-sm font-semibold">A distribuição aparecerá aqui.</p><p className="mt-1 max-w-xs text-xs text-muted-foreground">Crie e classifique orçamentos para acompanhar o funil comercial.</p></div></div>}<div className="mt-2 grid grid-cols-3 gap-2">{chartData.map((entry) => <div key={entry.key} className="rounded-xl bg-muted/60 px-3 py-2"><span className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wide text-muted-foreground"><i className="h-2 w-2 rounded-full" style={{ backgroundColor: STATUS_COLORS[entry.key] }} />{entry.label}</span><b className="mt-1 block text-sm">{compactNumber(entry.count)}</b></div>)}</div></CardContent></Card>
      <Card className="border-border/70 shadow-sm"><CardContent className="p-6"><div className="mb-4 flex items-start justify-between"><div><p className="text-sm font-bold">Valor por status</p><p className="mt-1 text-xs text-muted-foreground">Montante financeiro agrupado pela situação da proposta.</p></div><BarChart3 className="h-5 w-5 text-primary" /></div>{hasStatusData ? <div className="h-[260px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData} margin={{ top: 12, left: -12, right: 4, bottom: 0 }}><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: "currentColor", fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} width={48} tickFormatter={(value) => `R$ ${Math.round(value / 1000)}k`} tick={{ fill: "currentColor", fontSize: 10 }} /><Tooltip cursor={{ fill: "rgba(120, 113, 108, 0.08)" }} formatter={(value: number) => [money(value), "Valor"]} /><Bar dataKey="value" radius={[8, 8, 2, 2]}>{chartData.map((entry) => <Cell key={entry.key} fill={STATUS_COLORS[entry.key]} />)}</Bar></BarChart></ResponsiveContainer></div> : <div className="grid h-[260px] place-items-center rounded-2xl border border-dashed border-border text-center"><div><WalletCards className="mx-auto h-7 w-7 text-muted-foreground"/><p className="mt-3 text-sm font-semibold">Nenhum valor para comparar.</p><p className="mt-1 max-w-xs text-xs text-muted-foreground">Os gráficos usam apenas os valores reais dos orçamentos cadastrados.</p></div></div>}<div className="mt-2 rounded-xl bg-muted/60 p-3"><div className="flex items-center justify-between text-xs"><span className="font-semibold text-muted-foreground">Total orçado ativo</span><b>{money(data?.quotedTotal)}</b></div><div className="mt-2 flex items-center justify-between text-xs"><span className="font-semibold text-muted-foreground">Faturamento aprovado</span><b className="text-emerald-700 dark:text-emerald-300">{money(data?.approvedRevenue)}</b></div></div></CardContent></Card></section>

    <section><Card className="border-border/70 shadow-sm"><CardContent className="p-6"><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-red-500/10 text-red-700 dark:text-red-300"><AlertTriangle className="h-5 w-5" /></span><div><p className="text-sm font-bold">Alertas de validade</p><p className="mt-1 text-xs text-muted-foreground">Propostas pendentes vencidas ou com validade nos próximos {data?.alertThresholdDays ?? 7} dias.</p></div></div><Button size="sm" variant="outline" onClick={() => setLocation("/orcamentos")}>Ver todos <ArrowRight className="ml-2 h-3.5 w-3.5" /></Button></div>{expirationAlerts.length ? <div className="grid gap-3 lg:grid-cols-2 xl:grid-cols-3">{expirationAlerts.map((alert) => { const label = alert.severity === "expired" ? `${Math.abs(alert.daysRemaining)} dia(s) vencido` : alert.severity === "today" ? "Vence hoje" : `${alert.daysRemaining} dia(s) restante(s)`; const style = ALERT_STYLE[alert.severity as keyof typeof ALERT_STYLE]; return <div key={alert.id} className={`rounded-xl border p-3 ${style}`}><button onClick={() => setLocation(`/orcamentos/${alert.id}`)} className="flex w-full min-w-0 items-center gap-3 text-left transition hover:brightness-95"><CalendarDays className="h-5 w-5 shrink-0"/><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="truncate text-sm font-bold">#{alert.quoteNumber} · {alert.clientName || "Cliente não informado"}</p><ArrowRight className="h-4 w-4 shrink-0"/></div><p className="mt-1 text-xs font-semibold">{label} · {dateOnly(alert.validUntil)}</p><p className="mt-1 text-xs opacity-70">{money(alert.total)}</p></div></button><div className="mt-3 grid grid-cols-2 gap-2"><Button size="sm" variant="outline" className="h-8 border-current/25 bg-background/55 px-2 text-[11px] hover:bg-background" onClick={() => copyReminder(alert)}><Copy className="mr-1 h-3.5 w-3.5"/>Copiar</Button><Button size="sm" variant="outline" className="h-8 border-current/25 bg-background/55 px-2 text-[11px] hover:bg-background" onClick={() => sendReminder(alert)}><MessageCircle className="mr-1 h-3.5 w-3.5"/>WhatsApp</Button></div></div>; })}</div> : <div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-border px-6 py-8 text-center"><CalendarDays className="h-7 w-7 text-emerald-600"/><p className="mt-3 text-sm font-semibold">Nenhuma validade crítica no momento.</p><p className="mt-1 text-xs text-muted-foreground">O painel monitora rascunhos e propostas em aberto dentro do prazo configurado.</p></div>}</CardContent></Card></section>

    <section className="grid gap-6 lg:grid-cols-[1.4fr_0.9fr]"><Card className="border-border/70 shadow-sm"><CardContent className="p-6"><div className="mb-6 flex items-center justify-between"><div><p className="text-sm font-bold">Produtos mais cotados</p><p className="mt-1 text-xs text-muted-foreground">Ranking calculado a partir dos itens dos orçamentos.</p></div><Trophy className="h-5 w-5 text-[#c7a715]" /></div>{data?.ranking.length ? <div className="space-y-4">{data.ranking.map((product, index) => <div key={product.description} className="flex items-center gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-muted font-display text-sm font-bold">{String(index + 1).padStart(2, "0")}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{product.description}</p><p className="mt-0.5 text-xs text-muted-foreground">{compactNumber(product.quantity)} unidades em {compactNumber(product.occurrences)} inclusão(ões)</p></div><div className="h-2 w-20 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-[#e5c936]" style={{ width: `${Math.max(12, Math.round((product.quantity / (data.ranking[0]?.quantity || 1)) * 100))}%` }} /></div></div>)}</div> : <div className="rounded-2xl border border-dashed border-border p-8 text-center"><p className="text-sm font-semibold">O ranking aparecerá aqui.</p><p className="mt-1 text-xs text-muted-foreground">Cadastre produtos e inclua itens em orçamentos para gerar métricas.</p></div>}</CardContent></Card><Card className="border-border/70 shadow-sm"><CardContent className="flex h-full flex-col p-6"><p className="text-sm font-bold">Atalhos de gestão</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">Organize o catálogo antes de montar uma nova proposta.</p><div className="mt-6 space-y-2"><Button variant="outline" className="h-11 w-full justify-between" onClick={() => setLocation("/catalogo")}>Gerenciar catálogo <ArrowRight className="h-4 w-4" /></Button><Button variant="outline" className="h-11 w-full justify-between" onClick={() => setLocation("/orcamentos")}>Consultar propostas <ArrowRight className="h-4 w-4" /></Button><Button variant="outline" className="h-11 w-full justify-between" onClick={() => setLocation("/configuracoes")}>Configurar loja <ArrowRight className="h-4 w-4" /></Button></div></CardContent></Card></section>
  </div>;
}
