import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { money } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { CircleDollarSign, Landmark } from "lucide-react";
import { useLocation } from "wouter";

const meta = { open: { label: "Em aberto", className: "bg-sky-500/10 text-sky-700" }, partial: { label: "Parcial", className: "bg-amber-500/15 text-amber-800" }, paid: { label: "Recebida", className: "bg-emerald-500/10 text-emerald-700" }, overdue: { label: "Vencida", className: "bg-red-500/10 text-red-700" }, cancelled: { label: "Cancelada", className: "bg-slate-500/10 text-slate-700" } } as const;

export function QuoteFinancePanel({ quoteId, quoteStatus }: { quoteId: number; quoteStatus: "draft" | "open" | "approved" | "lost" }) {
  const [, setLocation] = useLocation(); const { data: receivables = [], isLoading } = trpc.finance.byQuote.useQuery({ quoteId });
  const outstanding = receivables.reduce((sum, receivable) => sum + receivable.remainingAmount, 0); const received = receivables.reduce((sum, receivable) => sum + receivable.receivedAmount, 0);
  return <Card className="border-border/70 shadow-sm"><CardHeader className="border-b border-border bg-muted/30 pb-4"><CardTitle className="flex items-center gap-2 font-display text-lg"><Landmark className="h-4 w-4 text-primary"/>Controle de pagamentos</CardTitle></CardHeader><CardContent className="pt-5">{isLoading ? <p className="text-sm text-muted-foreground">Atualizando carteira…</p> : receivables.length ? <div className="space-y-3"><div className="grid grid-cols-2 gap-2"><div className="rounded-xl bg-emerald-500/10 p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-emerald-800 dark:text-emerald-300">Recebido</p><p className="mt-1 font-display text-lg font-bold text-emerald-900 dark:text-emerald-200">{money(received)}</p></div><div className="rounded-xl bg-sky-500/10 p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-sky-800 dark:text-sky-300">Saldo</p><p className="mt-1 font-display text-lg font-bold text-sky-900 dark:text-sky-200">{money(outstanding)}</p></div></div><div className="space-y-2">{receivables.slice(0, 4).map((receivable) => { const status = meta[receivable.status]; return <div key={receivable.id} className="flex items-center justify-between gap-2 rounded-lg bg-muted/50 p-2 text-xs"><span>{receivable.installmentNumber}/{receivable.installmentCount} · vence {new Intl.DateTimeFormat("pt-BR").format(new Date(receivable.dueDate))}</span><Badge variant="secondary" className={status.className}>{status.label}</Badge></div>; })}</div></div> : <div className="text-center"><CircleDollarSign className="mx-auto h-7 w-7 text-muted-foreground"/><p className="mt-3 text-sm font-semibold">Nenhuma cobrança vinculada.</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{quoteStatus === "approved" ? "Salve novamente o orçamento aprovado para criar a carteira." : "Ao aprovar o orçamento, as parcelas serão criadas automaticamente."}</p></div>}<Button className="mt-4 w-full" size="sm" variant="outline" onClick={() => setLocation("/financeiro")}>Abrir financeiro</Button></CardContent></Card>;
}
